// Date de pornire pentru auto-completare - un punct de plecare rezonabil
// pentru piata din Romania, folosit doar cat timp nu exista inca istoric
// propriu. Odata ce service-ul finalizeaza fise reale, acelea au prioritate
// (vezi merge-ul din fileStore.getAutocompleteData) - astea sunt doar o
// baza, nu date fixe.

export const SEED_MARCI_MODELE = {
  Dacia: ['Logan', 'Sandero', 'Duster', 'Spring', 'Jogger', 'Dokker'],
  Volkswagen: ['Golf', 'Passat', 'Polo', 'Tiguan', 'Touran', 'Jetta'],
  Renault: ['Clio', 'Megane', 'Scenic', 'Captur', 'Kadjar', 'Talisman'],
  Ford: ['Focus', 'Fiesta', 'Kuga', 'Mondeo', 'EcoSport', 'Puma'],
  Opel: ['Astra', 'Corsa', 'Insignia', 'Mokka', 'Zafira', 'Vectra'],
  Skoda: ['Octavia', 'Fabia', 'Superb', 'Kodiaq', 'Rapid', 'Kamiq'],
  BMW: ['Seria 1', 'Seria 3', 'Seria 5', 'X1', 'X3', 'X5'],
  'Mercedes-Benz': ['Clasa A', 'Clasa C', 'Clasa E', 'GLC', 'Sprinter', 'Vito'],
  Audi: ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7'],
  Toyota: ['Corolla', 'Yaris', 'RAV4', 'Auris', 'Avensis', 'C-HR'],
  Hyundai: ['i10', 'i20', 'i30', 'Tucson', 'Elantra', 'Santa Fe'],
  Kia: ['Rio', 'Ceed', 'Sportage', 'Picanto', 'Sorento'],
  Peugeot: ['208', '308', '3008', '2008', '5008', '508'],
  Citroen: ['C3', 'C4', 'C5', 'Berlingo', 'C-Elysee'],
  Fiat: ['Punto', '500', 'Tipo', 'Ducato', 'Panda', 'Doblo'],
  Seat: ['Ibiza', 'Leon', 'Arona', 'Ateca'],
  Nissan: ['Qashqai', 'Micra', 'Juke', 'X-Trail', 'Note'],
  Honda: ['Civic', 'CR-V', 'Jazz', 'Accord'],
  Mazda: ['3', '6', 'CX-5', '2'],
  Volvo: ['S60', 'V40', 'XC60', 'XC90'],
  'Land Rover': ['Discovery', 'Range Rover', 'Freelander', 'Evoque'],
  Suzuki: ['Swift', 'Vitara', 'SX4', 'Jimny'],
  Mitsubishi: ['ASX', 'Outlander', 'Lancer', 'Colt'],
  Chevrolet: ['Aveo', 'Cruze', 'Spark']
}

// Fara preturi - variaza prea mult intre furnizori/marci de piese ca sa aiba
// sens o valoare implicita; ramane doar sugestia de denumire.
export const SEED_PIESE = [
  'Filtru ulei',
  'Filtru aer',
  'Filtru polen',
  'Filtru combustibil',
  'Filtru motorina',
  'Ulei motor',
  'Ulei cutie viteze',
  'Lichid frana',
  'Antigel',
  'Lichid servodirectie',
  'Lichid parbriz',
  'Placute frana fata',
  'Placute frana spate',
  'Discuri frana fata',
  'Discuri frana spate',
  'Saboti frana',
  'Furtun frana',
  'Senzor placute frana',
  'Amortizor fata',
  'Amortizor spate',
  'Arc suspensie',
  'Bucsa stabilizator',
  'Bara stabilizatoare',
  'Rulment roata',
  'Triunghi suspensie',
  'Cap de bara',
  'Kit distributie',
  'Curea alternator',
  'Bujii',
  'Bujii incandescente',
  'Bobina de inductie',
  'Injector',
  'Pompa combustibil',
  'Pompa apa',
  'Termostat',
  'Garnitura chiuloasa',
  'Senzor oxigen (lambda)',
  'Kit ambreiaj',
  'Rulment ambreiaj',
  'Planetara',
  'Burduf planetara',
  'Baterie auto',
  'Alternator',
  'Electromotor',
  'Bec far',
  'Bec semnalizare',
  'Siguranta electrica',
  'Senzor ABS',
  'Anvelopa',
  'Janta',
  'Parbriz',
  'Oglinda retrovizoare',
  'Lamele stergator',
  'Amortizor haion',
  'Radiator racire',
  'Radiator clima',
  'Compresor clima',
  'Toba esapament',
  'Catalizator',
  'Senzor parcare'
]

// Fara preturi, la fel ca piesele - manopera difera prea mult intre ateliere
// ca sa aiba sens o valoare implicita; ramane doar sugestia de denumire.
export const SEED_LUCRARI = [
  'Schimb ulei motor',
  'Schimb filtru ulei',
  'Schimb filtru aer',
  'Schimb filtru polen',
  'Schimb filtru combustibil',
  'Schimb placute frana fata',
  'Schimb placute frana spate',
  'Schimb discuri frana fata',
  'Schimb discuri frana spate',
  'Schimb kit distributie',
  'Schimb curea alternator',
  'Schimb baterie',
  'Schimb bujii',
  'Schimb amortizor',
  'Schimb kit ambreiaj',
  'Schimb rulment roata',
  'Geometrie roti',
  'Echilibrare roti (set)',
  'Schimb anvelope (set 4)',
  'Vulcanizare',
  'Diagnoza computerizata',
  'Revizie generala',
  'Schimb ulei cutie viteze',
  'Schimb pompa apa',
  'Schimb termostat',
  'Reparatie sistem esapament',
  'Schimb alternator',
  'Schimb electromotor',
  'Incarcare freon clima',
  'Verificare sistem clima',
  'Inspectie tehnica periodica (ITP)'
]
