// Date de pornire pentru auto-completare - un punct de plecare rezonabil
// pentru piata din Romania, folosit doar cat timp nu exista inca istoric
// propriu. Odata ce service-ul finalizeaza fise reale, acelea au prioritate
// (vezi merge-ul din fileStore.getAutocompleteData) - astea sunt doar o
// baza, nu date fixe.

export const SEED_MARCI_MODELE = {
  Dacia: ['Logan', 'Sandero', 'Duster', 'Spring', 'Jogger', 'Dokker', 'Lodgy', 'Solenza', 'Nova'],
  Volkswagen: [
    'Golf',
    'Passat',
    'Polo',
    'Tiguan',
    'Touran',
    'Jetta',
    'Up!',
    'Arteon',
    'Sharan',
    'Caddy',
    'Transporter',
    'Beetle',
    'Scirocco'
  ],
  Renault: [
    'Clio',
    'Megane',
    'Scenic',
    'Captur',
    'Kadjar',
    'Talisman',
    'Twingo',
    'Laguna',
    'Master',
    'Kangoo',
    'Fluence',
    'Espace'
  ],
  Ford: [
    'Focus',
    'Fiesta',
    'Kuga',
    'Mondeo',
    'EcoSport',
    'Puma',
    'Ka',
    'S-Max',
    'Galaxy',
    'Transit',
    'Transit Connect',
    'B-Max'
  ],
  Opel: [
    'Astra',
    'Corsa',
    'Insignia',
    'Mokka',
    'Zafira',
    'Vectra',
    'Meriva',
    'Combo',
    'Crossland',
    'Grandland',
    'Antara',
    'Agila'
  ],
  Skoda: ['Octavia', 'Fabia', 'Superb', 'Kodiaq', 'Rapid', 'Kamiq', 'Scala', 'Yeti', 'Karoq', 'Roomster'],
  BMW: ['Seria 1', 'Seria 2', 'Seria 3', 'Seria 4', 'Seria 5', 'Seria 7', 'X1', 'X2', 'X3', 'X5', 'X6', 'Z4'],
  'Mercedes-Benz': [
    'Clasa A',
    'Clasa B',
    'Clasa C',
    'Clasa E',
    'Clasa S',
    'GLA',
    'GLC',
    'GLE',
    'Sprinter',
    'Vito',
    'Citan',
    'CLA'
  ],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'TT'],
  Toyota: [
    'Corolla',
    'Yaris',
    'RAV4',
    'Auris',
    'Avensis',
    'C-HR',
    'Aygo',
    'Land Cruiser',
    'Hilux',
    'Camry',
    'Prius'
  ],
  Hyundai: ['i10', 'i20', 'i30', 'Tucson', 'Elantra', 'Santa Fe', 'Kona', 'ix35', 'Accent', 'Getz'],
  Kia: ['Rio', 'Ceed', 'Sportage', 'Picanto', 'Sorento', 'Stonic', 'Niro', 'Sephia', 'Venga'],
  Peugeot: ['108', '208', '308', '3008', '2008', '5008', '508', '407', 'Partner', 'Boxer', '206', '207'],
  Citroen: ['C1', 'C3', 'C4', 'C5', 'Berlingo', 'C-Elysee', 'Jumpy', 'C3 Aircross', 'Xsara', 'Saxo'],
  Fiat: ['Punto', '500', 'Tipo', 'Ducato', 'Panda', 'Doblo', '500X', 'Freemont', 'Bravo', 'Albea'],
  Seat: ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Toledo', 'Alhambra', 'Cordoba'],
  Nissan: ['Qashqai', 'Micra', 'Juke', 'X-Trail', 'Note', 'Navara', 'Leaf', 'Almera', 'Primera'],
  Honda: ['Civic', 'CR-V', 'Jazz', 'Accord', 'HR-V', 'Insight'],
  Mazda: ['2', '3', '6', 'CX-3', 'CX-5', 'CX-30', 'MX-5'],
  Volvo: ['S40', 'S60', 'S90', 'V40', 'V50', 'V60', 'XC40', 'XC60', 'XC90'],
  'Land Rover': [
    'Discovery',
    'Discovery Sport',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport',
    'Freelander',
    'Defender'
  ],
  Suzuki: ['Swift', 'Vitara', 'SX4', 'Jimny', 'Ignis', 'S-Cross', 'Baleno'],
  Mitsubishi: ['ASX', 'Outlander', 'Lancer', 'Colt', 'Pajero', 'L200', 'Space Star'],
  Chevrolet: ['Aveo', 'Cruze', 'Spark', 'Captiva', 'Trax', 'Lacetti', 'Matiz'],
  'Alfa Romeo': ['Giulietta', 'Giulia', 'Stelvio', 'Mito', '147', '156', '159'],
  Lancia: ['Ypsilon', 'Delta', 'Musa', 'Thema'],
  Mini: ['Cooper', 'Countryman', 'Clubman', 'One'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
  Subaru: ['Impreza', 'Forester', 'Outback', 'XV', 'Legacy'],
  SsangYong: ['Korando', 'Rexton', 'Tivoli', 'Actyon', 'Kyron'],
  Lexus: ['IS', 'RX', 'NX', 'CT', 'ES'],
  Jaguar: ['XE', 'XF', 'F-Pace', 'E-Pace', 'XJ'],
  Porsche: ['Cayenne', 'Macan', 'Panamera', '911', 'Boxster'],
  Smart: ['Fortwo', 'Forfour'],
  'DS Automobiles': ['DS3', 'DS4', 'DS7'],
  Isuzu: ['D-Max', 'Trooper'],
  Daewoo: ['Matiz', 'Nubira', 'Cielo', 'Lanos'],
  Rover: ['25', '45', '75'],
  Saab: ['9-3', '9-5'],
  Chery: ['Tiggo', 'QQ'],
  MG: ['ZS', 'HS', '3'],
  Iveco: ['Daily']
}

// Fara preturi - variaza prea mult intre furnizori/marci de piese ca sa aiba
// sens o valoare implicita; raman doar sugestii de denumire.
export const SEED_PIESE = [
  // Filtre
  'Filtru ulei',
  'Filtru aer',
  'Filtru polen',
  'Filtru combustibil',
  'Filtru motorina',
  'Filtru particule (FAP/DPF)',
  // Lichide/uleiuri
  'Ulei motor',
  'Ulei cutie viteze',
  'Ulei diferential',
  'Lichid frana',
  'Antigel',
  'Lichid servodirectie',
  'Lichid parbriz',
  'Aditiv combustibil',
  // Frane
  'Placute frana fata',
  'Placute frana spate',
  'Discuri frana fata',
  'Discuri frana spate',
  'Saboti frana',
  'Furtun frana',
  'Senzor placute frana',
  'Etrier frana',
  'Cilindru frana',
  'Servofrana',
  'Vas lichid frana',
  // Suspensie/directie
  'Amortizor fata',
  'Amortizor spate',
  'Arc suspensie',
  'Bucsa stabilizator',
  'Bara stabilizatoare',
  'Bieleta directie',
  'Rulment roata',
  'Triunghi suspensie',
  'Cap de bara',
  'Cremaliera directie',
  'Pompa servodirectie',
  'Burduf cremaliera',
  'Rulment cutie directie',
  // Motor
  'Kit distributie',
  'Curea distributie',
  'Lant distributie',
  'Curea alternator',
  'Rola intinzatoare',
  'Rola ghidaj curea',
  'Bujii',
  'Bujii incandescente',
  'Bobina de inductie',
  'Injector',
  'Pompa combustibil',
  'Pompa apa',
  'Pompa ulei',
  'Termostat',
  'Garnitura chiuloasa',
  'Senzor oxigen (lambda)',
  'Senzor arbore cotit',
  'Senzor arbore came',
  'Senzor MAP',
  'Senzor MAF (debitmetru)',
  'Turbina (turbosuflanta)',
  'Intercooler',
  'Vas expansiune',
  'Furtun radiator',
  'Radiator racire',
  'Radiator clima',
  'Compresor clima',
  'Ventilator racire',
  'Rezistenta ventilator',
  // Ambreiaj/transmisie
  'Kit ambreiaj',
  'Disc ambreiaj',
  'Placa presiune ambreiaj',
  'Rulment ambreiaj',
  'Cilindru ambreiaj principal',
  'Cilindru ambreiaj secundar',
  'Cablu ambreiaj',
  'Planetara',
  'Burduf planetara',
  'Rulment cutie viteze',
  'Simering',
  // Electrica
  'Baterie auto',
  'Alternator',
  'Electromotor',
  'Bec far',
  'Bec semnalizare',
  'Siguranta electrica',
  'Senzor ABS',
  'Releu',
  'Motoras stergator',
  'Motoras geam electric',
  'Macara geam electric',
  // Caroserie/exterior
  'Anvelopa',
  'Janta',
  'Parbriz',
  'Luneta',
  'Geam lateral',
  'Oglinda retrovizoare',
  'Lamele stergator',
  'Amortizor haion',
  'Toba esapament',
  'Catalizator',
  'Senzor parcare',
  'Broasca usa',
  'Maner usa',
  'Balama usa',
  'Grila fata',
  'Bara fata',
  'Bara spate',
  'Aripa fata',
  'Aripa spate',
  'Capota motor',
  'Far fata',
  'Stop spate'
]

// Fara preturi, la fel ca piesele - manopera difera prea mult intre ateliere
// ca sa aiba sens o valoare implicita; raman doar sugestii de denumire.
export const SEED_LUCRARI = [
  'Schimb ulei motor',
  'Schimb filtru ulei',
  'Schimb filtru aer',
  'Schimb filtru polen',
  'Schimb filtru combustibil',
  'Schimb filtru particule (FAP/DPF)',
  'Schimb placute frana fata',
  'Schimb placute frana spate',
  'Schimb discuri frana fata',
  'Schimb discuri frana spate',
  'Schimb saboti frana',
  'Reparatie etrier frana',
  'Purjare instalatie frana',
  'Schimb kit distributie',
  'Schimb curea alternator',
  'Schimb rola intinzatoare',
  'Schimb baterie',
  'Schimb bujii',
  'Schimb bujii incandescente',
  'Schimb injector',
  'Curatare/decarbonizare injectoare',
  'Schimb pompa combustibil',
  'Schimb pompa apa',
  'Schimb pompa ulei',
  'Schimb termostat',
  'Schimb turbina',
  'Reparatie turbina',
  'Schimb amortizor',
  'Schimb arc suspensie',
  'Schimb bucsa stabilizator',
  'Schimb bieleta directie',
  'Schimb rulment roata',
  'Schimb cremaliera directie',
  'Reparatie sistem directie',
  'Geometrie roti',
  'Echilibrare roti (set)',
  'Schimb anvelope (set 4)',
  'Montaj/demontaj anvelope',
  'Vulcanizare',
  'Schimb kit ambreiaj',
  'Reparatie cutie viteze',
  'Schimb ulei cutie viteze',
  'Schimb simering',
  'Diagnoza computerizata',
  'Resetare martor service',
  'Revizie generala',
  'Verificare sistem clima',
  'Incarcare freon clima',
  'Igienizare instalatie clima',
  'Reparatie sistem esapament',
  'Schimb alternator',
  'Schimb electromotor',
  'Reparatie instalatie electrica',
  'Schimb far/stop',
  'Reglaj faruri',
  'Inlocuire parbriz',
  'Reparatie parbriz (lipire cioburi)',
  'Reparatie caroserie',
  'Vopsitorie partiala',
  'Polish caroserie',
  'Spalare tapiterie',
  'Depanare la domiciliu',
  'Tractare auto',
  'Pregatire pentru ITP',
  'Inspectie tehnica periodica (ITP)'
]
